from typing import Dict, Any, List
from .base_agent import BaseAgent
from ..models.pipeline import StoryRequest, StoryScene
from ..services.openai_service import OpenAIService
from ..core.config import settings


class StoryGeneratorAgent(BaseAgent):
    def __init__(self, config: Dict[str, Any] = None):
        super().__init__("StoryGenerator", config)
        self.openai_service = None
        if settings.openai_api_key:
            try:
                self.openai_service = OpenAIService()
            except ValueError as e:
                self.log_error(f"Failed to initialize OpenAI service: {e}")
        
    async def process(self, input_data: StoryRequest) -> Dict[str, Any]:
        self.log_info(f"Generating story for: {input_data.story_idea}")
        
        if self.openai_service:
            complete_story = await self._generate_complete_story_with_ai(input_data.story_idea, input_data.num_slides)
            scenes = await self._break_into_scenes_with_ai(complete_story, input_data.num_slides)
        else:
            self.log_info("Using placeholder story generation (no OpenAI API key)")
            complete_story = await self._generate_complete_story_placeholder(input_data.story_idea)
            scenes = await self._break_into_scenes_placeholder(complete_story, input_data.num_slides)
        
        return {
            "complete_story": complete_story,
            "scenes": scenes
        }
        
    async def _generate_complete_story_with_ai(self, story_idea: str, num_slides: int) -> str:
        self.log_info("Generating complete story narrative with ChatGPT")
        return await self.openai_service.generate_story(story_idea, num_slides)
        
    async def _break_into_scenes_with_ai(self, story: str, num_slides: int) -> List[StoryScene]:
        self.log_info(f"Breaking story into {num_slides} scenes with ChatGPT")
        
        scene_contents = await self.openai_service.break_story_into_scenes(story, num_slides)
        
        scenes = []
        for i, content in enumerate(scene_contents):
            scene = StoryScene(
                scene_number=i + 1,
                content=content
            )
            scenes.append(scene)
            
        return scenes
        
    async def _generate_complete_story_placeholder(self, story_idea: str) -> str:
        self.log_info("Generating placeholder story narrative")
        
        return f"""
        {story_idea}
        
        This is a placeholder story that would be generated by ChatGPT.
        The story would be expanded from the initial idea into a full narrative
        with proper character development, plot progression, and engaging content
        suitable for presentation slides.
        
        To use AI generation, add your OpenAI API key to the .env file.
        """
        
    async def _break_into_scenes_placeholder(self, story: str, num_slides: int) -> List[StoryScene]:
        self.log_info(f"Breaking story into {num_slides} placeholder scenes")
        
        scenes = []
        for i in range(num_slides):
            scene = StoryScene(
                scene_number=i + 1,
                content=f"Scene {i + 1}: This is a placeholder scene content that would be intelligently extracted from the complete story using ChatGPT. Each scene would represent a logical segment of the narrative suitable for one slide."
            )
            scenes.append(scene)
            
        return scenes